import './globals.css';
import { Inter } from 'next/font/google';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { ProvidersUser } from '@/components/Providers';
import { Providers } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersUser>
          <Header />
          <main className="container">
            <Providers>{children}</Providers>
          </main>
          <Footer />
        </ProvidersUser>
      </body>
    </html>
  );
}
